apiVersion: batch/v1
kind: Job
metadata:
  name: workload-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: workload-init
        image: ctring/cockroach
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "workload"
          - "init"
          - "kv"
          - "--drop"
          - "--insert-count=1000"
          - "--min-block-bytes=100"
          - "--max-block-bytes=100"
          - "--regions=us-east-1,us-east-2"
          - "--single-replica"
          - "postgresql://root@cockroachdb.us-east-1:26257?sslmode=disable"
      restartPolicy: "Never"