# Example: cat workload-run.yaml | REGION=0 THETA=0.1 LOCAL_PCT=100 DURATION=5 NAMESPACE=us-east-1 envsubst | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: workload-run$SUFFIX
  labels:
    app: cockroachdb

spec:
  containers:
  - name: workload-run
    image: ctring/cockroach
    imagePullPolicy: IfNotPresent
    command:
      - "/cockroach/cockroach"
      - "workload"
      - "run"
      - "kv"
      - "--batch=1"
      - "--statements=10"
      - "--insert-count=50000000"
      - "--min-block-bytes=100"
      - "--max-block-bytes=100"
      - "--regions=$REGIONS"
      - "--read-percent=0"
      - "--region-idx=$REGION_IDX"
      - "--hot=$HOT"
      - "--local-region-percent=$LOCAL_PCT"
      - "--duration=${DURATION}s"
      - "--concurrency=${CONCURRENCY}"
      - "--update"
      - "postgresql://root@cockroachdb.${NAMESPACE}:26257?sslmode=disable"
  restartPolicy: "Never"