apiVersion: v1
kind: Pod
metadata:
  name: workload-init
  labels:
    app: cockroachdb

spec:
  containers:
  - name: workload-init
    image: ctring/cockroach
    imagePullPolicy: IfNotPresent
    command:
      - "/cockroach/cockroach"
      - "workload"
      - "init"
      - "kv"
      - "--drop"
      - "--insert-count=50000000"
      - "--min-block-bytes=100"
      - "--max-block-bytes=100"
      - "--regions=$REGIONS"
      - "--single-replica"
      - "postgresql://root@cockroachdb.$LOCAL_REGION:26257?sslmode=disable"
  restartPolicy: "Never"