# eksctl create cluster -f eksctl/ap-northeast-2.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: ap-northeast-2

vpc:
  subnets:
    public:
      ap-northeast-2a: { id: subnet-0c05e15bb1eb2cb39 }
      ap-northeast-2b: { id: subnet-037d17d54007acece }
      ap-northeast-2d: { id: subnet-0b77cbaa48cf042ea }

managedNodeGroups:
  - name: workers
    instanceType: m5.xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-0ac3fd56ca6b946d7