# eksctl create cluster -f eksctl/ap-northeast-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: ap-northeast-1

vpc:
  subnets:
    public:
      ap-northeast-1a: { id: subnet-0e16430fc4f55394b }
      ap-northeast-1c: { id: subnet-01f21ff0937063580 }
      ap-northeast-1d: { id: subnet-09f5757b70b66c7a5 }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-0f66a325f7ea5fd30
  - name: clients
    instanceType: c5.xlarge
    spot: true
    desiredCapacity: 1
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-0f66a325f7ea5fd30