# eksctl create cluster -f eksctl/ap-southeast-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: ap-southeast-1

vpc:
  subnets:
    public:
      ap-southeast-1a: { id: subnet-0482f8623e86e8cad }
      ap-southeast-1b: { id: subnet-091aaee4d46f29097 }
      ap-southeast-1c: { id: subnet-0e2d70fc6ec12c67a }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-06b2eeb8fdf0f4953
  - name: clients
    instanceType: c5.xlarge
    spot: true
    desiredCapacity: 1
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-06b2eeb8fdf0f4953