# eksctl create cluster -f eksctl/ap-southeast-2.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: ap-southeast-2

vpc:
  subnets:
    public:
      ap-southeast-2a: { id: subnet-0545759ea9802b3d0 }
      ap-southeast-2b: { id: subnet-0f5507b90b466758f }
      ap-southeast-2c: { id: subnet-00bd0c56765705b80 } 

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: false
    desiredCapacity: 3
    securityGroups:
      attachIDs:
        - sg-02114264b66f924ae
  - name: clients
    instanceType: c5.xlarge
    spot: false
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-02114264b66f924ae