# eksctl create cluster -f eksctl/eu-west-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: eu-west-1

vpc:
  subnets:
    public:
      eu-west-1a: { id: subnet-0ffc60f2e1a784c05 }
      eu-west-1b: { id: subnet-097b92d96accfde20 }
      eu-west-1c: { id: subnet-0765b6609bf1ab069 }
  sharedNodeSecurityGroup: sg-0bbce0eb0d1d85aee

managedNodeGroups:
  - name: workers
    instanceType: m5.xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true