# eksctl create cluster -f eksctl/us-east-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-01ffdf1e8d2d11bce }
      us-east-1b: { id: subnet-0f2ae7a9189cd2786 }
      us-east-1c: { id: subnet-0346cab72850ef316 }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-0f92e3d1b0cc49df6
  - name: clients
    instanceType: c5.xlarge
    spot: true
    desiredCapacity: 1
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-0f92e3d1b0cc49df6