# eksctl create cluster -f eksctl/us-west-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: us-west-1

vpc:
  subnets:
    public:
      us-west-1a: { id: subnet-05f98b4f44c64847e }
      us-west-1b: { id: subnet-08f4dcbd56e6814c1 }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: false
    desiredCapacity: 3
    securityGroups:
      attachIDs:
        - sg-046193268c5f5e771
  - name: clients
    instanceType: c5.xlarge
    spot: false
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-046193268c5f5e771