# eksctl create cluster -f eksctl/us-west-2.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cockroachdb
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-0c7307ae51cd54955 }
      us-west-2b: { id: subnet-017e607e654b73f35 }
      us-west-2c: { id: subnet-06401fc941a2b272e }
      us-west-2d: { id: subnet-08b07ebe86eeeaffa }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 3
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-00d71ca4d6219ecc8
  - name: clients
    instanceType: c5.xlarge
    spot: true
    desiredCapacity: 1
    ssh:
      allow: true
    securityGroups:
      attachIDs:
        - sg-00d71ca4d6219ecc8