apiVersion: v1
kind: Pod
metadata:
  name: workload-init
  labels:
    app: cockroachdb
spec:
  containers:
  - name: workload-init
    image: ctring/cockroach:preload
    imagePullPolicy: IfNotPresent
    command:
      - "/cockroach/cockroach"
      - "workload"
      - "init"
      - "kv"
      - "--drop"
      - "--insert-count=100000"
      - "--regions=region-0,region-1,region-2"
      - "--single-replica"
      - "postgresql://root@cockroachdb.region-0:26257?sslmode=disable"
  restartPolicy: "Never"
