us-east-1: |
  us-east-1.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 3.87.149.81 54.167.149.245 52.6.245.109 {
        force_tcp
    }
  }
us-east-2: |
  us-east-2.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 3.19.226.116 18.189.140.142 3.134.14.239 {
        force_tcp
    }
  }
us-west-1: |
  us-west-1.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 184.169.235.175 50.18.119.118 {
        force_tcp
    }
  }
us-west-2: |
  us-west-2.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 52.89.27.178 52.25.248.207 52.11.174.232 54.185.126.99 {
        force_tcp
    }
  }
eu-west-1: |
  eu-west-1.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 52.16.115.225 52.215.149.113 {
        force_tcp
    }
  }
eu-west-2: |
  eu-west-2.svc.cluster.local:53 {
    log
    errors
    ready
    cache 10
    forward . 35.178.0.90 18.170.168.150 18.170.168.69 {
        force_tcp
    }
  }
# ap-northeast-1: |
#   ap-northeast-1.svc.cluster.local:53 {
#     log
#     errors
#     ready
#     cache 10
#     forward . 35.73.250.79 54.178.71.245 3.114.1.160 {
#         force_tcp
#     }
#   }
# ap-northeast-2: |
#   ap-northeast-2.svc.cluster.local:53 {
#     log
#     errors
#     ready
#     cache 10
#     forward . 54.180.68.107 3.38.123.35 3.35.215.104 {
#         force_tcp
#     }
#   }
# ap-southeast-1: |
#   ap-southeast-1.svc.cluster.local:53 {
#     log
#     errors
#     ready
#     cache 10
#     forward . 3.0.236.59 18.138.6.248 52.221.98.37 {
#         force_tcp
#     }
#   }
# ap-southeast-2: |
#   ap-southeast-2.svc.cluster.local:53 {
#     log
#     errors
#     ready
#     cache 10
#     forward . 54.79.215.215 54.66.205.249 3.105.9.127 {
#         force_tcp
#     }
#   }