apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 10
        loop
        reload
        loadbalance
    }
    us-east-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
    us-east-2.svc.cluster.local:53 {
       log
       errors
       ready
       cache 10
       forward . 18.215.120.107 3.210.105.133 3.235.209.152 {
           force_tcp
       }
     }
    eu-west-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
    eu-west-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
    ap-northeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
    ap-northeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
    ap-southeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.132.26.221 3.23.246.188 {
          force_tcp
      }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
