apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 10
        loop
        reload
        loadbalance
    }
    us-east-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 44.194.150.211 3.226.208.198 {
          force_tcp
      }
    }
    us-east-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 18.190.34.5 3.22.76.39 18.219.202.208 {
          force_tcp
      }
    }
    eu-west-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 35.179.61.21 18.168.250.73 18.134.78.4 {
          force_tcp
      }
    }
    ap-northeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 18.180.201.161 3.114.21.43 52.199.1.40 {
          force_tcp
      }
    }
    ap-northeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.37.149.134 52.79.205.134 3.38.50.101 {
          force_tcp
      }
    }
    ap-southeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 13.250.164.105 13.213.235.123 18.139.59.20 {
          force_tcp
      }
    }
    ap-southeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 13.211.104.174 13.236.234.164 13.239.154.103 {
          force_tcp
      }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
