apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 10
        loop
        reload
        loadbalance
    }
    us-east-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 34.227.240.89 3.223.73.164 50.16.182.10 {
          force_tcp
      }
    }
    us-east-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.134.70.122 18.220.86.91 3.132.156.79 {
          force_tcp
      }
    }
    eu-west-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 54.155.204.112 46.137.44.252 54.77.16.182 {
          force_tcp
      }
    }
    ap-northeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 35.73.250.79 54.178.71.245 3.114.1.160 {
          force_tcp
      }
    }
    ap-northeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 54.180.68.107 3.38.123.35 3.35.215.104 {
          force_tcp
      }
    }
    ap-southeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.0.236.59 18.138.6.248 52.221.98.37 {
          force_tcp
      }
    }
    ap-southeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 54.79.215.215 54.66.205.249 3.105.9.127 {
          force_tcp
      }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
