apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 10
        loop
        reload
        loadbalance
    }
    us-east-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.87.149.81 54.167.149.245 52.6.245.109 {
          force_tcp
      }
    }
    us-west-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 184.169.235.175 50.18.119.118 {
          force_tcp
      }
    }
    us-west-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 52.89.27.178 52.25.248.207 52.11.174.232 54.185.126.99 {
          force_tcp
      }
    }
    eu-west-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 52.16.115.225 52.215.149.113 {
          force_tcp
      }
    }
    eu-west-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 35.178.0.90 18.170.168.150 18.170.168.69 {
          force_tcp
      }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
