apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 10
        loop
        reload
        loadbalance
    }
    us-east-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 44.196.39.222 3.218.121.43 3.225.7.123 {
          force_tcp
      }
    }
    us-east-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 18.116.57.216 18.188.250.232 3.16.7.179 {
          force_tcp
      }
    }
    eu-west-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 34.248.43.228 54.228.5.240 63.33.123.155 {
          force_tcp
      }
    }
    ap-northeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 3.115.137.78 52.194.8.237 52.196.76.106 {
          force_tcp
      }
    }
    ap-northeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 15.165.187.14 54.180.215.202 3.37.64.147 {
          force_tcp
      }
    }
    ap-southeast-1.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 13.228.123.162 13.228.241.136 13.213.189.198 {
          force_tcp
      }
    }
    ap-southeast-2.svc.cluster.local:53 {
      log
      errors
      ready
      cache 10
      forward . 13.238.5.7 13.211.243.121 3.104.231.200 {
          force_tcp
      }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
