apiVersion: v1
kind: ConfigMap
metadata:
 name: coredns
 namespace: kube-system
data:
 Corefile: |
   .:53 {
       errors
       ready
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 10
       loop
       reload
       loadbalance
   }
   us-east-1.svc.cluster.local:53 {
       log
       errors
       ready
       cache 10
       forward . 3.209.208.205 52.204.197.97 34.228.133.77 {
            force_tcp
       }
   }